name: Cron Build

on: 
  schedule:
    - cron: "12 6 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
env:
  CI: true
  PIPENV_VENV_IN_PROJECT: true
  SCRAPY_SETTINGS_MODULE: city_scrapers.settings.prod
  WAYBACK_ENABLED: true
  AUTOTHROTTLE_MAX_DELAY: 30.0
  AUTOTHROTTLE_START_DELAY: 1.5
  AUTOTHROTTLE_TARGET_CONCURRENCY: 3.0
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  NEXTDOOR_USERNAME: ${{ secrets.NEXTDOOR_USERNAME }}
  NEXTDOOR_PASSWORD: ${{ secrets.NEXTDOOR_PASSWORD }}
  # OPENVPN_USER: ${{ secrets.OPENVPN_USER }}
  # OPENVPN_PASS: ${{ secrets.OPENVPN_PASS }}
  # OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: pipenv sync --dev
        env:
          PIPENV_DEFAULT_PYTHON_VERSION: 3.7

      - name: Run scrapers
        run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH
          ./.deploy.sh

      - name: Combine output feeds
        run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH
          pipenv run scrapy combinefeeds -s LOG_ENABLED=False
